version: "3.8"
services:
  teleprompter:
    image: teleprompter
    build:
      context: .
      args:
        - APP_DOMAIN=easypi.tv
    init: true
    ports:
      - "3000:3000"
      - "8080:8080"
    restart: unless-stopped
