version: "3.8"
services:
  mitmproxy:
    image: mitmproxy/mitmproxy
    command: mitmweb --web-host 0.0.0.0
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./data:/home/mitmproxy/.mitmproxy
    restart: unless-stopped
