version: "3.8"

services:
  darkice:
    image: vimagick/darkice
    volumes:
      - ./data/etc:/etc/darkice
      - ./data/var:/var/lib/darkice
    restart: unless-stopped

networks:
  default:
    external: true
    name: icecast_default
