version: "3.8"
services:
  squid:
    image: vimagick/squid
    ports:
      - "3128:3128/tcp"
      - "3130:3130/udp"
    volumes:
      - ./data/etc/squid.conf:/etc/squid/squid.conf
      - ./data/cache:/var/cache/squid
      - ./data/log:/var/log/squid
    stop_signal: SIGKILL
    restart: unless-stopped
