version: '3.8'

services:

  chrome:
    image: selenium/node-chrome:3.141.59
    ports:
      - "5555:5555"
    environment:
      - HUB_HOST=10.0.0.21
      - HUB_PORT=4444
      - REMOTE_HOST=http://10.0.0.22:5555
      - NODE_MAX_INSTANCES=2
      - NODE_MAX_SESSION=2
    shm_size: 2gb
    restart: unless-stopped
