version: "3.8"
services:
  frps:
    image: vimagick/frp
    volumes:
      - ./data/frps.ini:/opt/frp/frps.ini
    healthcheck:
      test: ["CMD", "curl", "-f", "-u", "admin:admin", "http://127.0.0.1:7500/healthz"]
      interval: 1m
      timeout: 5s
    network_mode: host
    restart: unless-stopped
