version: "3.8"
services:
  mosquitto:
    image: easypi/mosquitto-arm64
    ports:
      - "1883:1883"
    volumes:
      - ./data/etc:/etc/mosquitto
      - ./data/var:/var/lib/mosquitto
    restart: unless-stopped
