version: "3.8"
services:
  icecast:
    image: vimagick/icecast-arm
    ports:
      - "8000:8000"
    volumes:
      # ./data/etc:/etc/icecast:ro
      - ./data/log:/var/log/icecast:rw
    restart: unless-stopped
