version: "3.8"

services:
  statsd:
    image: vimagick/statsd
    ports:
      - "8126:8126/tcp"
      - "8125:8125/udp"
    volumes:
      - ./data/config.js:/opt/statsd/config.js
    restart: unless-stopped

networks:
  default:
    external: true
    name: graphite_default
